/**:
  ros__parameters:
    #予測された軌道に対する障害物の衝突をチェックし、衝突が見つかった場合に診断エラーを発行するモジュールである。
    #launchで無効化されているっぽい
    # Node
    update_rate: 10.0

    # Core
    delay_time: 0.03 # delay time of vehicle [s]
    footprint_margin: 0.0 # margin for footprint [m]
    max_deceleration: 1.5 # max deceleration [m/ss]
    resample_interval: 0.3 # interval distance to resample point cloud [m]
    search_radius: 5.0 # search distance from trajectory to point cloud [m]
