/**:
  ros__parameters:
    # -- Node Configurations --
    planning_algorithm: "astar"
    waypoints_velocity: 1.0
    update_rate: 1.0
    th_arrived_distance_m: 1.0
    th_stopped_time_sec: 1.0
    th_stopped_velocity_mps: 0.02
    th_course_out_distance_m: 0.1
    vehicle_shape_margin_m: 0.15
    replan_when_obstacle_found: true
    replan_when_course_out: true

    # -- Configurations common to the all planners --
    # base configs
    time_limit: 100000.0
    # robot configs # TODO replace by vehicle_info
    robot_length: 3.117
    robot_width: 1.265
    robot_base2back: 0.510
    minimum_turning_radius: 3.0
    maximum_turning_radius: 5.0
    turning_radius_size: 10
    # search configs
    theta_size: 100
    angle_goal_range: 3.0
    curve_weight: 0.4
    reverse_weight: 2.0
    lateral_goal_range: 0.5
    longitudinal_goal_range: 1.0
    # costmap configs
    obstacle_threshold: 100

    # -- A* search Configurations --
    astar:
      only_behind_solutions: false
      use_back: true
      distance_heuristic_weight: 0.5