# see AvoidanceParameters description in avoidance_module_data.hpp for description.　ros2 topic echo /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/avoidance_debug_message_array
/**:
  ros__parameters:
    avoidance:
      resample_interval_for_planning: 0.1               # [m]回避計画パスのパス再サンプル間隔。
      resample_interval_for_output: 0.3                 # [m]
      detection_area_right_expand_dist: 0.3             # 回避のためにレーンを拡大する。Lanelet expand length for right side to find avoidance target vehicles.[m]
      detection_area_left_expand_dist: 0.3              # Lanelet expand length for left side to find avoidance target vehicles.  [m]
      drivable_area_right_bound_offset: 0.0             # [m]
      drivable_area_left_bound_offset: 0.0              # [m]
      object_envelope_buffer: 0.2                       # [m] オブジェクトを少し大きく取る。

      # avoidance module common setting
      enable_bound_clipping: false
      enable_avoidance_over_same_direction: true #同じ方向の横車線に車線変更して回避するか。
      enable_avoidance_over_opposite_direction: true #反対車線まで車線変更して回避するか。
      enable_update_path_when_object_is_gone: false #1回生成した回避パスをObjectが検出されないようになっても使い続けるか。
      enable_force_avoidance_for_stopped_vehicle: true #停車しているvehicleに対して強制的にavoidを行うか。
      enable_safety_check: false #安全チェック, Jerkしか確認しない。
      #回避経路が生成でき、周囲の交通状況により回避を実行するべきではないと判断した時にYieldManuvergで、回避を実行するかいなかを決定する。
      enable_yield_maneuver: false #Flag to enable yield maneuver.
      disable_path_update: false

      # for debug
      publish_debug_marker: true #Flag to publish debug marker (set `false` as default since it takes considerable cost)
      print_debug_info: true  #Flag to print debug info (set `false` as default since it takes considerable cost)

      # avoidance is performed for the object type with true
      target_object:
        car: true
        truck: false
        bus: false
        trailer: false
        unknown: true
        bicycle: false
        motorcycle: false
        pedestrian: false

      # For target object filtering
      target_filtering:
        # filtering moving objects
        threshold_speed_object_is_stopped: 1.0          # 回避するオブジェクト種類. これより大きい速度の物体は回避されない。[m/s]
        threshold_time_object_is_moving: 5.0            # オブジェクトが動いているという判定時間[s]。チャタリングの防止。
        threshold_time_force_avoidance_for_stopped_vehicle: 10.0 # [s]
        # detection range, egoとObjectとの距離と、ObjectがGoalより後ろにない。
        object_check_force_avoidance_clearance: 2.0    # [m]
        object_check_forward_distance: 30.0            # これより遠くのオブジェクトは回避しない。[m] Def::150
        object_check_backward_distance: 0.0             # 自車両より後ろのチェック。これより近くのオブジェクトは回避しない。詳細はDocsで確認。このParamよりObjectが後ろにいない。このParamにマイナスが付く？[m]def:2m
        object_check_goal_distance: 20.0                # [m]
        # filtering parking objects　信号待ち車両の除外。センターライン付近で止まっている車両の除外
        threshold_distance_object_is_on_center: 0.0     # センターラインに付近にいるオブジェクトを回避しないため。センターラインからx mのオブジェクトは回避しない。[m]
        object_check_shiftable_ratio: 0.0               # [Max 1] Objが駐車しているかどうかの判定。これより高ければ回避を実行する。
        object_check_min_road_shoulder_width: 0.0       # [m]
        # lost object compensation
        object_last_seen_threshold: 2.0 #[s] チャタリングの防止。障害物が消えてもしばらく保持する。大きいと過検出が増える
      

      # For safety check 今は無効化 Yield Manuverに使う。
      #エゴの未来位置と物体の予測経路から衝突の危険性を判断します。時間地平(safety_check_time_horizon)におけるエゴの将来位置を計算し、
      #物体の予測経路を物体の将来位置として使用します。
      safety_check:
        safety_check_backward_distance: 0.1            # [m] #後方チェックする距離 Def::0.5
        safety_check_time_horizon: 5.0                  # [s] この時間で衝突する可能性を判断する。
        safety_check_idling_time: 1.5                    # [s] 横マージン計算のため。Def 1.5
        safety_check_accel_for_rss: 2.5                  # [m/ss]　RSSに基づく縦方向のマージン計算に使用されるアクセル定数。横マージン計算のため。　Def 2.5
        safety_check_hysteresis_factor: 2.0              # [-]チャタリング防止に使用されるヒステリシス係数。

      # For avoidance maneuver
      avoidance:
        # avoidance lateral parameters.横方向にどれだけ回避するのかを決定する。
        lateral: 
          lateral_collision_margin: 0.23                 # [m]
          lateral_collision_safety_buffer: 0.51          # [m]
          lateral_passable_safety_buffer: 0.0           # [m]
          road_shoulder_safety_margin: 0.0              # [m]
          avoidance_execution_lateral_threshold: 0.3
          max_right_shift_length: 3.0
          max_left_shift_length: 3.0
        # avoidance distance parameters
        longitudinal:
          prepare_time: 0.0                             # [s]
          longitudinal_collision_safety_buffer: 0.0     # [m]
          min_prepare_distance: 0.0                     # [m]
          min_avoidance_distance: 0.0                  # [m]
          min_nominal_avoidance_speed: 1.0              # [m/s]
          min_sharp_avoidance_speed: 1.0                # [m/s]

      # For yield maneuver.回避操作を実行しないとき。
      yield:
        yield_velocity: 2.78                            # まずはこの速度に減速する。その後Yieldが継続され車両が回避目標に接近した場合は停止する。[m/s]

      # For stop maneuver 回避操作が許可されていない状況、または降伏操作における最低停止距離。Yield Manuverがfalseでも出る。
      #ダンボールおじさんの停止位置。
      stop:
        min_distance: 3.0                              # [m]
        max_distance: 6.0                              # 回避操作が許可されない状況、または降伏操作における最大停止距離。[m]

      constraints:
        # vehicle slows down under longitudinal constraints
        use_constraints_for_decel: false                # [-]

        # lateral constraints
        lateral:
          nominal_lateral_jerk: 0.2                     # [m/s3]
          max_lateral_jerk: 1.0                         # [m/s3]

        # longitudinal constraints
        longitudinal:
          nominal_deceleration: -1.0                    # [m/ss]
          nominal_jerk: 0.5                             # [m/sss]
          max_deceleration: -2.0                        # [m/ss]
          max_jerk: 1.0
          # For prevention of large acceleration while avoidance
          min_avoidance_speed_for_acc_prevention: 3.0   # [m/s]
          max_avoidance_acceleration: 0.5               # [m/ss]
      #SafetyChack横方向マージン計算
      target_velocity_matrix:
        col_size: 2
        matrix:
          [1.38, 2.0,                                  # target velocity [m/s]
           0.01, 0.03]                                  # margin [m]

#//         D5
#//      |<---->|                               D4
#//      |<----------------------------------------------------------------------->|
#// +-----------+            D1                 D2                      D3         +-----------+
#// |           |        |<------->|<------------------------->|<----------------->|           |
#// |    ego    |======= x ======= x ========================= x ==================|    obj    |
#// |           |    stop_point  avoid                       avoid                 |           |
#// +-----------+                start                        end                  +-----------+
#//
#// D1: p.min_prepare_distance
#// D2: min_avoid_distance
#// D3: longitudinal_avoid_margin_front (margin + D5)
#// D4: o_front.longitudinal
#// D5: base_link2front