/**:
  ros__parameters:
    # system
    over_stop_velocity_warn_thr: 1.65       # used to check if the optimization exceeds the input velocity on the stop point

    # motion state constraints
    max_velocity: 1.389      # 変更の必要なし。5.004km/h max velocity limit [m/s]
    stop_decel: 0.0         # deceleration at a stop point[m/ss]

    # path extraction parameters 
    extract_ahead_dist: 50.0         # forward trajectory distance used for planning [m]
    extract_behind_dist: 5.0          # backward trajectory distance used for planning [m]
    delta_yaw_threshold: 1.0472       # 恐らく使っていない。Allowed delta yaw between ego pose and trajectory pose [radian]

    # external velocity limit parameter
    margin_to_insert_external_velocity_limit: 0.3   #  恐らく使っていない？margin distance to insert external velocity limit [m]
  
    # stop velocity
    stopping_velocity: 0.1    # 1km/h change target velocity to this value before v=0 point [m/s]
    stopping_distance: 1.0    # この距離の手前になったら上の速度が適用される。現在無効化。distance for the stopping_velocity [m]. 0 means the stopping velocity is not applied.

    # curve parameters(Apply lateral limit)曲がるときに適用される。上2つが曲がる時のスピードに影響。
    max_lateral_accel: 0.07             # max lateral acceleration limit [m/ss]
    min_curve_velocity: 0.0            # 曲がるときの最低速度。min velocity at lateral acceleration limit and steering angle rate limit [m/s]
    decel_distance_before_curve: 4.0   # slow speed distance before a curve for lateral acceleration limit
    decel_distance_after_curve: 0.5    # slow speed distance after a curve for lateral acceleration limit
    min_decel_for_lateral_acc_lim_filter: -6.5  # deceleration limit applied in the lateral acceleration filter to avoid sudden braking [m/ss]

    # steering angle rate limit parameters. 入らないようにしてある。
    max_steering_angle_rate: 286.0            # maximum steering angle rate [degree/s]
    resample_ds: 0.05                         # distance between trajectory points [m]
    curvature_threshold: 50.0                # if curvature > curvature_threshold, steeringRateLimit is triggered [1/m]
    curvature_calculation_distance: 0.1      # distance of points while curvature is calculating [m]

    # resampling parameters for optimization　ここはあまりいじる必要はない？
    max_trajectory_length: 200.0        # max trajectory length for resampling [m]
    min_trajectory_length: 50.0        # min trajectory length for resampling [m]
    resample_time: 2.0                  # resample total time for dense sampling [s]
    dense_resample_dt: 0.2              # resample time interval for dense sampling [s]
    dense_min_interval_distance: 0.1    # minimum points-interval length for dense sampling [m]
    sparse_resample_dt: 0.5             # resample time interval for sparse sampling [s]
    sparse_min_interval_distance: 4.0   # minimum points-interval length for sparse sampling [m]

    # engage & replan parameters 発進時(engage)
    replan_vel_deviation: 5.53         # velocity deviation to replan initial velocity [m/s]
    engage_velocity: 0.1              # 発進時の速度制限。1.38より大きいとエラーーengage velocity threshold [m/s] (if the trajectory velocity is higher than this value, use this velocity for engage vehicle speed)
    engage_acceleration: 0.05           # 発進時の加速度制限　engage acceleration [m/ss] (use this acceleration when engagement)
    engage_exit_ratio: 0.5             # exit engage sequence to normal velocity planning when the velocity exceeds engage_exit_ratio x engage_velocity.
    stop_dist_to_prohibit_engage: 0.6   # if the stop point is in this distance, the speed is set to 0 not to move the vehicle [m]

    #Apply JerkFilter, L2, Linf, orAnalytical 

    # resampling parameters for post process
    post_max_trajectory_length: 300.0        # max trajectory length for resampling [m]
    post_min_trajectory_length: 30.0         # min trajectory length for resampling [m]
    post_resample_time: 10.0                 # resample total time for dense sampling [s]
    post_dense_resample_dt: 0.1              # resample time interval for dense sampling [s]
    post_dense_min_interval_distance: 0.1    # minimum points-interval length for dense sampling [m]
    post_sparse_resample_dt: 0.1             # resample time interval for sparse sampling [s]
    post_sparse_min_interval_distance: 1.0   # minimum points-interval length for sparse sampling [m]



