/**:
  ros__parameters:
    distance_threshold_list:
      #UNKNOWN, CAR, TRUCK, BUS,  TRAILER, MOTORBIKE, BICYCLE,PEDESTRIAN
      [19.0,     19.0, 19.0,   19.0,  19.0,     19.0,       19.0,    19.0]         #UNKNOWN
