/**:
  ros__parameters:
    # -- system --
    traj_resample_dist: 0.2665         # path resampling interval [m]リサンプリングにおけるWayPointの距離 Def::0.1
    use_steer_prediction: false     # flag for using steer prediction (do not use steer measurement) 現在ステアリング情報を取得する際に予測値を用いるか。Falseで良いかと。
    admissible_position_error: 5.0  # stop mpc calculation when error is larger than the following value
    admissible_yaw_error_rad: 1.57  # stop mpc calculation when error is larger than the following value

    # -- path smoothing --　基本的に無効でいい気がする。
    enable_path_smoothing: true   # flag for path smoothing
    path_filter_moving_ave_num: 10 # param of moving average filter for path smoothing
    curvature_smoothing_num_traj: 10        # point-to-point index distance used in curvature calculation (for trajectory): curvature is calculated from three points p(i-num), p(i), p(i+num)
    curvature_smoothing_num_ref_steer: 10   # point-to-point index distance used in curvature calculation (for steer command reference): curvature is calculated from three points p(i-num), p(i), p(i+num)

    # -- trajectory extending -- MPCはPathの終点における姿勢角を考慮していない。経路終点を姿勢方向に延長することで、姿勢角を考慮できるようになり制御性能が向上する。軌道が終点の姿勢角を考慮して適切に定義されているならfalse
    extend_trajectory_for_end_yaw_control: true # flag of trajectory extending for terminal yaw control.ヨーエンド制御のためにTrajを延長するかいなか。最後ぐにゃって曲がる。

    # -- mpc optimization -- inputは下げる。Weightは上げると、そのParamがより考慮される。
    qp_solver_type: "unconstraint_fast"          # optimization solver option (unconstraint_fast or osqp)パラメタの調整不足でosqpだとsolveできないときがある。解けないとMPC結果が出力されない。→止まる。
    mpc_prediction_horizon: 70                   # prediction horizon step トータルのMPC予想ステップ：多い方が良い。
    mpc_prediction_dt: 0.2                       # prediction horizon period [s]　少ない方が良い。
    mpc_weight_lat_error: 5.3                    # lateral error weight in matrix Q
    mpc_weight_heading_error: 4.1                # heading error weight in matrix Q かなり変わる。直進性。
    mpc_weight_heading_error_squared_vel: 0.3    # heading error * velocity weight in matrix Q
    mpc_weight_steering_input: 0.97               # steering error weight in matrix R
    mpc_weight_steering_input_squared_vel: 0.25  # steering error * velocity weight in matrix R
    mpc_weight_lat_jerk: 0.0                     # lateral jerk weight in matrix R
    mpc_weight_steer_rate: 0.0                   # steering rate weight in matrix R 
    mpc_weight_steer_acc: 0.000001               # steering angular acceleration weight in matrix R

    #Not Used
    mpc_low_curvature_weight_lat_error: 1.0                    # lateral error weight in matrix Q in low curvature point
    mpc_low_curvature_weight_heading_error: 1.0                # heading error weight in matrix Q in low curvature point
    mpc_low_curvature_weight_heading_error_squared_vel: 0.3    # heading error * velocity weight in matrix Q in low curvature point
    mpc_low_curvature_weight_steering_input: 0.1               # steering error weight in matrix R in low curvature point
    mpc_low_curvature_weight_steering_input_squared_vel: 0.25  # steering error * velocity weight in matrix R in low curvature point
    mpc_low_curvature_weight_lat_jerk: 1.0                     # lateral jerk weight in matrix R in low curvature point
    mpc_low_curvature_weight_steer_rate: 1.0                   # steering rate weight in matrix R in low curvature point
    mpc_low_curvature_weight_steer_acc: 0.000001               # steering angular acceleration weight in matrix R in low curvature point
    mpc_low_curvature_thresh_curvature: 0.0                    # threshold of curvature to use "low_curvature" parameter (recommend: 0.01~0.03)

    mpc_weight_terminal_lat_error: 6.0             # terminal lateral error weight in matrix Q to improve mpc stability 昔はもっと小さい
    mpc_weight_terminal_heading_error: 1.1       # terminal heading error weight in matrix Q to improve mpc stability　　昔はもっと小さい
    mpc_zero_ff_steer_deg: 0.5                   # threshold that feed-forward angle becomes zero
    mpc_acceleration_limit: 2.0                  # limit on the vehicle's acceleration
    mpc_velocity_time_constant: 0.61              # time constant used for velocity smoothing
    mpc_min_prediction_length: 5.0               # minimum prediction length

    # -- vehicle model --
    vehicle_model_type: "kinematics" # vehicle model type for mpc prediction. option is kinematics, kinematics_no_delay, and dynamics
    input_delay: 0.14                # steering input delay time for delay compensation
    vehicle_model_steer_tau: 0.1     # steering dynamics time constant (1d approximation) [s]
    steer_rate_lim_dps: 400.0         # steering angle rate limit [deg/s]
    acceleration_limit: 100.0          # acceleration limit for trajectory velocity modification [m/ss]
    velocity_time_constant: 0.61      # velocity dynamics time constant  for trajectory velocity modification [s]

    # -- lowpass filter for noise reduction --
    steering_lpf_cutoff_hz: 3.0 # cutoff frequency of lowpass filter for steering command [Hz]
    error_deriv_lpf_cutoff_hz: 5.0

    # stop state: steering command is kept in the previous value in the stop state.
    stop_state_entry_ego_speed: -3.0
    stop_state_entry_target_speed: -3.0
    converged_steer_rad: 0.1
    keep_steer_control_until_converged: false #ステアリング計算値が収束するまで、以前のステア値を用いるか
    new_traj_duration_time: 1.0
    new_traj_end_dist: 0.3

    # steer offset
    steering_offset:
      enable_auto_steering_offset_removal: true
      update_vel_threshold: 0.56
      update_steer_threshold: 0.035
      average_num: 1000
      steering_offset_limit: 0.02