/**:
  ros__parameters:
    module_list: #Module names managing in rtc_auto_mode_manager
      - "detection_area"
      - "avoidance_left"
      - "avoidance_right"

    default_enable_list: #Module names enabled auto mode at initialization
      - "detection_area"
      - "avoidance_left"
      - "avoidance_right"
