/**:
  ros__parameters:
  #最後のPredictionを担当
  #map_based_predictionは、地図の形状や周囲の環境に応じて、他の車両や歩行者の将来の進路（およびその確率）を予測するモジュールである。
    enable_delay_compensation: true #オブジェクトの位置に対する時間遅延補正を有効にするフラグ
    prediction_time_horizon: 10.0 #予測経路の予測時間 [s]
    prediction_sampling_delta_time: 0.5 #予測経路上の点のサンプリング時間[s]
    min_velocity_for_map_based_prediction: 10.39 #[m/s] Def::1.39マップベースの予測を、この値よりも速度が速いオブジェクトに適用する。
    min_crosswalk_user_velocity: 1.39 #[m/s]横断歩道利用者の進路予測における最低速度の使用
    dist_threshold_for_searching_lanelet: 3.0 #[m]
    delta_yaw_threshold_for_searching_lanelet: 0.785 #[rad]
    sigma_lateral_offset: 0.5 #[m]
    sigma_yaw_angle_deg: 5.0 #[angle degree]
    object_buffer_time_length: 2.0 #[s]
    history_time_length: 1.0 #[s]
    dist_threshold_for_lane_change_detection: 1.0 #[m]
    time_threshold_for_lane_change_detection: 5.0 #[s]
    cutoff_freq_of_velocity_for_lane_change_detection: 0.1 #[Hz]
    reference_path_resolution: 0.5 #[m]
