/**:
  ros__parameters:
    detection_area:
      stop_margin: 0.0 #車両がstop_lineの前に停止しようとするマージン
      use_dead_line: false #Deadlineを使うか否か
      dead_line_margin: 5.0 #後続車が自車と衝突するかどうかの閾値を無視する。？
      use_pass_judge_line: false #PassJudgelineを使うかいなか。
      state_clear_time: 2.0 #障害物がない状態で一定時間停止している場合、STOPPED状態に移行する。
