/**:
  ros__parameters:
    # Node
    update_rate: 10.0
    visualize_lanelet: true
    include_right_lanes: false
    include_left_lanes: false
    include_opposite_lanes: false
    include_conflicting_lanes: false

    # Core
    footprint_margin_scale: 0.8 #geometrymsg::PosewithCovari(自身の位置)とこのマージンスケールを用いて車体のフットプリントを作成 Default:1
    resample_interval: 0.3
    max_deceleration: 2.8 #制動距離を計算する際のMax acc
    delay_time: 0.1 #ブレーキを作動させてから実際に作動するまでのDelay。制動距離を計算するために使用。
    max_lateral_deviation: 1.0 #LaneDepartureではなく、Traj DeviationのためのParam
    max_longitudinal_deviation: 1.0
    max_yaw_deviation_deg: 60.0
    delta_yaw_threshold_for_closest_point: 1.570 #M_PI/2.0, delta yaw thres for closest point
    min_braking_distance: 0.0
